#!/bin/sh
export DISPLAY=:0
xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

kweb3 -ACZNDJK+-zbhrqfpoklgtjneduwxyavcsmi:#=?! 'http://mfuklc:password@localhost:1880/register'

